import {describePreview} from './preview-description.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {STLLoader} from 'three/addons/loaders/STLLoader.js';
import {createIcons, icons} from 'lucide';
import './style.css';
const icon=n=>`<i data-lucide="${n}"></i>`;
document.querySelector('#app').innerHTML=`
<header><a class="brand" href="#"><span class="brand-mark">${icon('box')}</span>cadforge<span class="beta">STUDIO</span></a><div class="doc-title"><span id="document-name">Untitled workspace</span><span class="saved" id="save-state">Local workspace</span></div><div class="header-actions"><a href="http://localhost:2719" target="_blank" class="lab-link">${icon('flask-conical')}Learning lab</a><button id="import">${icon('upload')}Import</button><button id="save-project" disabled>${icon('save')}Save project</button><button id="export" class="primary" disabled>${icon('download')}Export STL</button></div></header>
<div class="toolbar"><div class="tools"><button id="undo" title="Undo last committed change" disabled>${icon('undo-2')}</button><span class="divider"></span><button class="active" id="select-object">${icon('mouse-pointer-2')}Object</button><button id="select-region">${icon('scan')}Section</button><button id="fit">${icon('maximize')}Fit</button><button id="wire" title="Toggle mesh edges">${icon('grid-3x3')}</button></div><span class="toolbar-note" id="selection-hint">Import a model to start shaping</span><label class="units">Import units <select id="units"><option value="mm">mm</option><option value="cm">cm</option><option value="in">in</option></select></label></div>
<main><aside class="objects-panel"><div class="panel-heading">OBJECTS <span id="object-count">0</span></div><div id="objects"><p class="muted empty-list">Your model’s parts appear here.</p></div><div class="selection-details" id="selection-details" hidden><div class="panel-heading">SELECTION</div><h3 id="selection-name">Object</h3><div id="dimensions"></div><div id="region-options" hidden><label>Section radius <span id="radius-label">10 mm</span></label><input id="radius" type="range" min="2" max="80" value="10"><p class="muted">Click a surface to place the section. Orange bounds show exactly what can change.</p></div><button id="clear-selection" class="text-button">Clear selection</button></div><div class="sidebar-bottom"><span class="status-dot"></span> Files stay on this computer</div></aside>
<section id="viewport"><div id="canvas-host"></div><div id="marquee" hidden></div><div class="view-cube"><button id="iso-view">${icon('box')}<span>ISO</span></button><button id="top-view">TOP</button><button id="front-view">FRONT</button><button id="side-view">SIDE</button></div><div id="drop-zone"><div class="drop-icon">${icon('box')}</div><span class="eyebrow">START WITH ANY SHAPE</span><h1>Your model.<br>Your words.</h1><p>Drop a CAD file or reopen a saved project.<br>Select a part, then tell the agent what to change.</p><button id="browse" class="primary">${icon('upload')}Choose a model</button><span class="file-types">STL · STEP · CADForge project</span><button id="sample" class="sample-link">Or explore a sample model ${icon('arrow-up-right')}</button></div><div id="drag-overlay" hidden>Drop your CAD file to import</div><div class="viewport-footer"><span id="geometry-status">Orbit · drag &nbsp; Pan · right drag &nbsp; Zoom · scroll</span><span id="scale-note">Millimeters</span></div><div id="preview-banner" hidden><div><span class="eyebrow">CHANGE PREVIEW</span><strong id="preview-summary">Review the change</strong></div><button id="discard">Discard</button><button id="apply" class="primary">${icon('check')}Apply change</button></div><div id="busy" hidden><span class="spinner"></span><span id="busy-text">Working on your model…</span></div></section>
<aside class="agent-panel"><div class="agent-heading"><div class="agent-logo">${icon('sparkles')}</div><div><h2>Design with words</h2><span>Tell me what you want to change</span></div><button id="history-toggle" title="View learning and change history">${icon('history')}</button></div><div id="messages"><div class="welcome"><h3>A little more room?<br>A whole new direction?</h3><p>Select an object or a section in the workspace, then describe the change naturally.</p><div class="suggestions"><button data-prompt="Make this 2 cm wider">Make this 2 cm wider ${icon('arrow-up-right')}</button><button data-prompt="Move this 3 cm to the right">Move this 3 cm to the right ${icon('arrow-up-right')}</button><button data-prompt="Add a 10 by 10 by 5 mm box here">Add a section here ${icon('arrow-up-right')}</button></div><div class="learn-note">${icon('workflow')}<p>Edits are checked before you apply them. The agent keeps outcomes and reuses verified operations.</p></div></div></div><div id="history-panel" hidden></div><form id="prompt-form"><div id="context-pill" hidden>${icon('scan')}<span id="context-label">Selection</span></div><textarea id="prompt" rows="3" placeholder="Select something, then describe your change…" aria-label="Describe your CAD edit"></textarea><div class="composer-bottom"><span id="planner-status">Preview before applying</span><button class="send" id="send" type="submit" title="Preview edit" disabled>${icon('arrow-up')}</button></div></form><div class="agent-footnote">Geometry checks support edits; physical qualification is separate.</div></aside></main><input id="file-input" type="file" accept=".stl,.step,.stp,.cadforge" hidden><div id="toast" role="status" hidden></div>`;
createIcons({icons});
const $=id=>document.getElementById(id);
let state=null,selected=null,sectionMode=false,pending=null,meshObjects=[],selectionHelper=null,pointMarker=null,lastPoint=null,working=false,protectedMarkers=[];
const scene=new THREE.Scene();scene.background=new THREE.Color('#f4f7fa');scene.fog=new THREE.Fog('#f4f7fa',650,1600);
const renderer=new THREE.WebGLRenderer({antialias:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.setClearColor('#f4f7fa');$('canvas-host').appendChild(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive CAD workspace');
let camera=new THREE.PerspectiveCamera(38,1,.05,5000);camera.up.set(0,0,1);camera.position.set(170,-210,180);
const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.target.set(0,0,20);
scene.add(new THREE.HemisphereLight(0xffffff,0x8d9dad,2.4));const sun=new THREE.DirectionalLight(0xffffff,3);sun.position.set(80,-120,220);scene.add(sun);
const grid=new THREE.GridHelper(800,80,0xaac4d6,0xdce6ed);grid.rotation.x=Math.PI/2;grid.position.z=-.15;scene.add(grid);
const base=new THREE.Mesh(new THREE.PlaneGeometry(800,800),new THREE.MeshStandardMaterial({color:'#edf3f7',roughness:1,transparent:true,opacity:.3}));base.position.z=-.3;scene.add(base);
const axes=new THREE.AxesHelper(35);scene.add(axes);
function resize(){const r=$('canvas-host').getBoundingClientRect();renderer.setSize(r.width,r.height);if(camera.isOrthographicCamera){const half=(camera.top-camera.bottom)/2;camera.left=-half*r.width/r.height;camera.right=half*r.width/r.height}else camera.aspect=r.width/r.height;camera.updateProjectionMatrix()};new ResizeObserver(resize).observe($('canvas-host'));renderer.setAnimationLoop(()=>{orbit.update();renderer.render(scene,camera)});
const loader=new STLLoader(),raycaster=new THREE.Raycaster();
function toast(message){$('toast').textContent=message;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,6500)}
function busy(value,text='Working on your model…'){working=value;$('busy').hidden=!value;$('busy-text').textContent=text;$('send').disabled=value||!state;$('import').disabled=value;$('apply').disabled=value;}
async function api(path,options={}){const r=await fetch('/api'+path,options);if(!r.ok){let e;try{e=await r.json()}catch{e={detail:r.statusText}}throw Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail||e));}return r.json()}
const post=(path,data)=>api(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});
function fileURL(path){return '/api/file?path='+encodeURIComponent(path)}
function fit(){if(!meshObjects.length)return;if(camera.isOrthographicCamera){const r=renderer.domElement.getBoundingClientRect();camera=new THREE.PerspectiveCamera(38,r.width/r.height,.05,5000);camera.up.set(0,0,1);orbit.object=camera;}const box=new THREE.Box3();meshObjects.forEach(m=>box.expandByObject(m));const c=box.getCenter(new THREE.Vector3()),s=box.getSize(new THREE.Vector3()).length();orbit.target.copy(c);camera.position.copy(c).add(new THREE.Vector3(1,-1.35,1).multiplyScalar(s*1.3*Math.max(1,1/camera.aspect)));camera.near=Math.max(.01,s/2000);camera.far=Math.max(2000,s*50);camera.updateProjectionMatrix();}
async function drawParts(parts,fitView=false,preview=false){const meshes=await Promise.all(parts.map(async(p,i)=>{const response=await fetch(fileURL(p.stl_path));if(!response.ok)throw Error('Could not load exported geometry');const geometry=loader.parse(await response.arrayBuffer());geometry.computeBoundingBox();const mat=new THREE.MeshStandardMaterial({color:preview?'#74c9b4':i%2?'#6fa9be':'#91b8cc',roughness:.5,metalness:.12,side:THREE.DoubleSide});const m=new THREE.Mesh(geometry,mat);m.userData={part:p};const edge=new THREE.LineSegments(new THREE.EdgesGeometry(geometry,32),new THREE.LineBasicMaterial({color:'#3c6e86',transparent:true,opacity:.16}));m.add(edge);return m}));meshObjects.forEach(m=>{scene.remove(m);m.geometry.dispose();m.material.dispose()});meshObjects=meshes;meshes.forEach(m=>scene.add(m));if(fitView)fit();updateHighlight();}
function clearHelpers(){protectedMarkers.forEach(m=>{scene.remove(m);m.geometry.dispose();m.material.dispose()});protectedMarkers=[];if(selectionHelper){scene.remove(selectionHelper);selectionHelper=null}if(pointMarker){scene.remove(pointMarker);pointMarker=null}}
function updateHighlight(){clearHelpers();
 for(const f of pending?.protected_features||[]){const rings=f.profile?.rings||[{z:f.z_min,radius_mm:f.radius_mm},{z:f.z_max,radius_mm:f.radius_mm}];for(const ring of rings){const z=ring.z,radius=ring.radius_mm;const points=[];for(let i=0;i<=64;i++){const a=i*Math.PI/32;const local=[f.center[0]+radius*Math.cos(a),f.center[1]+radius*Math.sin(a),z],world=[0,0,0];(f.local_to_world_axes||[0,1,2]).forEach((axis,j)=>world[axis]=local[j]);points.push(new THREE.Vector3(...world))}const line=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0xe1a13d,depthTest:false}));line.renderOrder=5;scene.add(line);protectedMarkers.push(line)}}
meshObjects.forEach(m=>{m.material.emissive.set(m.userData.part.id===selected?.part_id?'#1e4d53':'#000000');m.material.emissiveIntensity=.14});if(!selected)return;const p=state.parts.find(p=>p.id===selected.part_id);if(!p)return;const bounds=selected.region?[selected.region.min,selected.region.max]:p.bounds;const b=new THREE.Box3(new THREE.Vector3(...bounds[0]),new THREE.Vector3(...bounds[1]));selectionHelper=new THREE.Box3Helper(b,selected.region?0xe5a23c:0x198c87);scene.add(selectionHelper);if(lastPoint){pointMarker=new THREE.Mesh(new THREE.SphereGeometry(Math.max(.35,b.getSize(new THREE.Vector3()).length()/120),16,16),new THREE.MeshBasicMaterial({color:'#eeaa42'}));pointMarker.position.fromArray(lastPoint);scene.add(pointMarker);}}
function updateSelection(){const p=state?.parts.find(p=>p.id===selected?.part_id);$('selection-details').hidden=!p;$('context-pill').hidden=!p;$('region-options').hidden=!sectionMode||!p;if(p){const bounds=selected.region?[selected.region.min,selected.region.max]:p.bounds;const size=bounds[1].map((v,i)=>v-bounds[0][i]);$('selection-name').textContent=selected.region?'Selected section':p.name;$('dimensions').innerHTML=size.map((v,i)=>`<div><span>${['Width · X','Depth · Y','Height · Z'][i]}</span><strong>${v.toFixed(2)} <small>mm</small></strong></div>`).join('');$('context-label').textContent=(selected.region?'Section of ':'')+p.name;$('selection-hint').textContent=selected.region?'Only the highlighted section can change':'Selected object · click a surface to place additions';}else $('selection-hint').textContent=state?'Click an object to select it':'Import a model to start shaping';updateHighlight();renderObjects()}
function selectPart(p,point=null,normal=null){lastPoint=point;selected={part_id:p.id,region:null,point,normal};if(sectionMode&&point){const r=+$('radius').value;selected.region={min:point.map((v,i)=>Math.max(v-r,p.bounds[0][i])),max:point.map((v,i)=>Math.min(v+r,p.bounds[1][i]))}}updateSelection()}
function renderObjects(){if(!state)return;$('objects').replaceChildren();state.parts.forEach((p,i)=>{const b=document.createElement('button');b.className='object-row'+(selected?.part_id===p.id?' selected':'');b.innerHTML=icon('box')+`<span></span><small>${i+1}</small>`;b.querySelector('span').textContent=p.name;b.onclick=()=>selectPart(p);$('objects').appendChild(b)});$('object-count').textContent=state.parts.length;createIcons({icons});}
async function useState(data,fitView=false){state=data;pending=null;$('preview-banner').hidden=true;$('drop-zone').hidden=true;$('document-name').textContent=state.name;$('save-state').textContent='Saved locally';$('export').disabled=false;$('save-project').disabled=false;$('send').disabled=false;$('undo').disabled=!state.parent_version;if(selected&&!state.parts.some(p=>p.id===selected.part_id))selected=null;await drawParts(state.parts,fitView);renderObjects();updateSelection();$('geometry-status').textContent=`${state.parts.reduce((n,p)=>n+p.triangles,0).toLocaleString()} triangles · ${state.parts.length} objects`;$('scale-note').textContent='X width · Y depth · Z height / mm';renderHistory();localStorage.setItem('cadforge-session',state.id)}
function message(role,text,extra=null){const div=document.createElement('div');div.className='message '+role;const label=document.createElement('span');label.className='message-label';label.textContent=role==='user'?'YOU':'CADFORGE';div.append(label);const p=document.createElement('p');p.textContent=text;div.append(p);if(extra)div.append(extra);$('messages').append(div);$('messages').scrollTop=$('messages').scrollHeight;return div}
function checksNode(checks){const d=document.createElement('details');d.className='checks';const items=checks||[],failed=items.filter(c=>!c.passed);d.open=failed.length>0;const summary=document.createElement('summary');summary.textContent=failed.length?`${failed.length} checks need attention`:`${items.length} geometry checks passed`;d.append(summary);items.forEach(c=>{const row=document.createElement('div');row.className=c.passed?'check-pass':'check-fail';row.textContent=(c.passed?'✓ ':'× ')+c.name.replaceAll('_',' ');row.title=typeof c.detail==='string'?c.detail:JSON.stringify(c.detail);d.append(row)});return d}
function previewExplanation(result){return describePreview(result,state)}
function learningNode(preview){
 const trials=preview.repair_trials||preview.checks?.find(c=>c.name==='repair_trials')?.detail||[];
 const learning=preview.learning;
 if(!trials.length&&!learning)return null;
 const d=document.createElement('div');d.className='learning-card';
 const heading=document.createElement('strong');heading.textContent=learning?.status==='reused'?'Saved repair reused':trials.some(t=>!t.accepted)?'Checked → corrected → checked again':'Operation checked';d.append(heading);
 for(const t of trials){const p=document.createElement('p');const human=t.strategy==='sharp'?'Direct section edit':'Smooth interior transition';p.textContent=(t.accepted?'✓ ':'× ')+human+' · '+(t.accepted?'passed':'rejected');d.append(p)}
 if(learning){const p=document.createElement('p');p.textContent=learning.narrative||learning.message||learning.status||'';d.append(p)}
 if(learning?.status==='audit_failed'&&preview.base_version&&preview.source_mesh_sha256){
  const retry=document.createElement('button');retry.textContent='Retry saving learning';
  retry.onclick=async()=>{retry.disabled=true;try{const receipt=await post(`/sessions/${preview.session_id}/previews/${preview.preview_id}/learning/retry`,{});preview.learning=receipt;retry.textContent='Learning outcome saved';const note=document.createElement('p');note.textContent=receipt.narrative||'Retained outcomes saved without rerunning geometry.';d.append(note)}catch(error){toast(error.message);retry.disabled=false}};
  d.append(retry);
 }
 if(trials.some(t=>t.accepted&&t.strategy!=='sharp')){const p=document.createElement('p');p.className='scope';p.textContent='The requested movement is reached inside the section; movement tapers toward its boundary. Outside vertices stay fixed. Review this transition before applying.';d.append(p)}
 return d;
}
function renderHistory(){const el=$('history-panel');el.replaceChildren();const title=document.createElement('h3');title.textContent='Change history';el.append(title);if(state?.history_trust==='imported-unverified'){const note=document.createElement('p');note.textContent='Imported history is reported provenance. Current geometry was checked on opening; past operation checks have not been rerun.';el.append(note)}for(const h of state?.history||[]){const p=document.createElement('p');p.textContent=h.description||h.operation||h.command?.op||(h.action==='undo'?'Undid previous change':'Imported model');el.append(p)}if(state?.learning){const p=document.createElement('pre');p.textContent=JSON.stringify(state.learning,null,2);el.append(p)}}
async function importFile(file){if(!file)return;busy(true,'Importing and checking geometry…');try{const form=new FormData();form.append('file',file);form.append('units',$('units').value);const data=await api('/import',{method:'POST',body:form});selected=null;await useState(data,true);message('agent',file.name.toLowerCase().endsWith('.cadforge')?`Reopened ${data.name} with applied changes and Undo history. Select a part to continue editing.`:`Imported ${file.name}. Select an object or switch to Section, then describe your change.`)}catch(e){toast(e.message);message('agent',e.message)}finally{busy(false)}}
$('import').onclick=$('browse').onclick=()=>$('file-input').click();$('file-input').onchange=e=>importFile(e.target.files[0]);
let drags=0;window.addEventListener('dragenter',e=>{e.preventDefault();drags++;$('drag-overlay').hidden=false});window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('dragleave',()=>{if(--drags<=0)$('drag-overlay').hidden=true});window.addEventListener('drop',e=>{e.preventDefault();drags=0;$('drag-overlay').hidden=true;importFile(e.dataTransfer.files[0])});
$('sample').onclick=async()=>{busy(true,'Opening sample…');try{await useState(await post('/sample',{}),true);message('agent','Sample opened. Click it to select, then try “make this 2 cm wider”.')}catch(e){toast(e.message)}finally{busy(false)}};
$('fit').onclick=fit;$('wire').onclick=()=>{meshObjects.forEach(m=>m.material.wireframe=!m.material.wireframe);$('wire').classList.toggle('active')};
$('select-object').onclick=()=>{sectionMode=false;$('select-object').classList.add('active');$('select-region').classList.remove('active');if(selected)selected.region=null;updateSelection()};$('select-region').onclick=()=>{sectionMode=true;$('select-region').classList.add('active');$('select-object').classList.remove('active');$('selection-hint').textContent='Click a section or drag a selection box · Alt-drag to orbit';$('region-options').hidden=!selected;};
$('radius').oninput=()=>{$('radius-label').textContent=$('radius').value+' mm';if(selected&&lastPoint)selectPart(state.parts.find(p=>p.id===selected.part_id),lastPoint)};
$('clear-selection').onclick=()=>{selected=null;lastPoint=null;updateSelection()};
let pointerStart,marqueeActive=false;
renderer.domElement.addEventListener('pointerdown',e=>{pointerStart=[e.clientX,e.clientY];if(sectionMode&&!e.altKey&&!working&&!pending&&e.button===0){marqueeActive=true;orbit.enabled=false;}});
renderer.domElement.addEventListener('pointermove',e=>{if(!marqueeActive||!pointerStart)return;const r=renderer.domElement.getBoundingClientRect();const x=Math.min(e.clientX,pointerStart[0])-r.left,y=Math.min(e.clientY,pointerStart[1])-r.top;Object.assign($('marquee').style,{left:x+'px',top:y+'px',width:Math.abs(e.clientX-pointerStart[0])+'px',height:Math.abs(e.clientY-pointerStart[1])+'px'});$('marquee').hidden=false;});
renderer.domElement.addEventListener('pointerup',e=>{
 const wasMarquee=marqueeActive;marqueeActive=false;orbit.enabled=true;$('marquee').hidden=true;
 if(working||pending||!state||!pointerStart)return;
 const distance=Math.hypot(e.clientX-pointerStart[0],e.clientY-pointerStart[1]);const r=renderer.domElement.getBoundingClientRect();
 if(wasMarquee&&distance>7){
  const x0=Math.min(e.clientX,pointerStart[0]),x1=Math.max(e.clientX,pointerStart[0]),y0=Math.min(e.clientY,pointerStart[1]),y1=Math.max(e.clientY,pointerStart[1]);let chosen=null,chosenPoints=[];
  for(const m of meshObjects){const positions=m.geometry.attributes.position,points=[];for(let i=0;i<positions.count;i++){const v=new THREE.Vector3().fromBufferAttribute(positions,i),q=v.clone().project(camera);const x=r.left+(q.x+1)/2*r.width,y=r.top+(1-q.y)/2*r.height;if(q.z>=-1&&q.z<=1&&x>=x0&&x<=x1&&y>=y0&&y<=y1)points.push(v)}if(points.length>chosenPoints.length){chosen=m;chosenPoints=points}}
  if(chosenPoints.length){const box=new THREE.Box3().setFromPoints(chosenPoints);box.expandByScalar(.0001);selected={part_id:chosen.userData.part.id,region:{min:box.min.toArray(),max:box.max.toArray()},point:box.getCenter(new THREE.Vector3()).toArray()};lastPoint=selected.point;updateSelection();$('selection-hint').textContent='Section selected through the model · orange bounds show the edit region';}else toast('No mesh vertices in that selection. Drag a larger section.');return;
 }
 if(distance>5)return;raycaster.setFromCamera(new THREE.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hits=raycaster.intersectObjects(meshObjects,false);if(hits.length){const hit=hits[0],normal=hit.face?.normal.clone().applyNormalMatrix(new THREE.Matrix3().getNormalMatrix(hit.object.matrixWorld)).normalize().toArray();selectPart(hit.object.userData.part,hit.point.toArray(),normal||null);}
});
$('prompt-form').onsubmit=async e=>{e.preventDefault();const request=$('prompt').value.trim();if(!request||!state||working)return;if(pending){toast('Apply or discard the current preview first.');return}message('user',request);$('prompt').value='';busy(true,'Understanding your request and checking the edit…');try{const result=await post(`/sessions/${state.id}/edit`,{request,selection:selected,base_revision:state.revision});const plannerLabel=result.planner==='sequence_planner'?'Checked sequence':result.planner?.startsWith('pydantic_ai')?'AI plan':result.planner==='offline_fallback'?'Offline fallback':'Offline parser';$('planner-status').textContent=plannerLabel+' · '+(result.preview?.accepted?'checks passed':result.clarification?'needs detail':'edit rejected');if(result.clarification){message('agent',result.clarification);return}const pv=result.preview;message('agent',previewExplanation(result),checksNode(pv?.checks));if(pv?.step_outcomes)for(const [i,step] of pv.step_outcomes.entries()){message('agent',`Step ${i+1}: ${step.request||step.command.op} — ${describePreview({preview:step,command:step.command,explanation:step.explanation},step.input_parts?{parts:step.input_parts}:state)}`,checksNode(step.checks));if(step.persistent_learning?.narrative)message('agent',step.persistent_learning.narrative);}if(pv?.protected_features?.length)message('agent',`${pv.protected_features.length} through-holes recognized. Orange rings mark the protected surfaces. Their positions and geometry are checked against the original mesh.`);const learn=learningNode(pv||{});if(learn)message('agent','Edit history',learn);if(result.learning_message)message('agent',result.learning_message);if(pv?.accepted){pending=pv;selected=pv.selection;lastPoint=selected?.point||null;await drawParts(pv.parts,false,true);updateSelection();$('preview-summary').textContent=previewExplanation(result);$('preview-banner').hidden=false;}else message('agent',pv?.error||'This edit did not pass the checks. Your model is unchanged.');}catch(e){message('agent',e.message)}finally{busy(false)}};
$('prompt').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('prompt-form').requestSubmit()}});document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('prompt').value=b.dataset.prompt;$('prompt').focus()});
$('apply').onclick=async()=>{if(!pending)return;busy(true,'Saving this version…');try{await useState(await post(`/sessions/${state.id}/commit`,{preview_id:pending.preview_id}));message('agent','Applied. The previous version is available in Undo.')}catch(e){toast(e.message)}finally{busy(false)}};
$('discard').onclick=async()=>{pending=null;$('preview-banner').hidden=true;await drawParts(state.parts);message('agent','Preview discarded. Your saved model is unchanged.')};
$('undo').onclick=async()=>{busy(true,'Restoring the previous version…');try{await useState(await post(`/sessions/${state.id}/undo`,{}));message('agent','Restored the previous version.')}catch(e){toast(e.message)}finally{busy(false)}};
$('save-project').onclick=()=>{if(!state||working)return;if(pending){toast('Apply or discard the preview before saving your project.');return}window.location.href=`/api/sessions/${state.id}/project`};
$('export').onclick=()=>{if(state)window.location.href=`/api/sessions/${state.id}/export`};$('history-toggle').onclick=async()=>{
 $('history-panel').hidden=!$('history-panel').hidden;$('messages').hidden=!$('history-panel').hidden;
 if(!$('history-panel').hidden){renderHistory();try{const data=await api('/learning');const title=document.createElement('h3');title.textContent='Learning from past edits';$('history-panel').append(title);const summary=document.createElement('p');summary.textContent=`${data.evidence.length} recorded previews · ${data.skills.length} saved strategy versions`; $('history-panel').append(summary);
 for(const e of data.evidence.slice(-12)){const card=document.createElement('div');card.className='learning-card';const title=document.createElement('strong');title.textContent=e.used_skill_id?'Saved strategy used':e.actual_correction?'Failure corrected':'Measured edit';card.append(title);const p=document.createElement('p');p.textContent=`${e.command?.op} on ${e.command?.axis?.toUpperCase()} · ${e.topology?.faces} triangles`;card.append(p);for(const t of e.trials||[]){const row=document.createElement('p');row.textContent=(t.accepted?'✓ ':'× ')+(t.strategy==='sharp'?'Direct section edit':'Interior transition')+' · '+(t.accepted?'passed':'rejected');card.append(row)}$('history-panel').append(card)}
 }catch(e){toast(e.message)}}
};
function view(axis){if(!meshObjects.length)return;const b=new THREE.Box3();meshObjects.forEach(m=>b.expandByObject(m));const center=b.getCenter(new THREE.Vector3()),size=b.getSize(new THREE.Vector3()).length()*1.35,r=renderer.domElement.getBoundingClientRect(),aspect=r.width/r.height;camera=new THREE.OrthographicCamera(-size*aspect/2,size*aspect/2,size/2,-size/2,.01,10000);camera.up.set(0,0,1);orbit.object=camera;orbit.target.copy(center);camera.position.copy(center).add(axis.multiplyScalar(size*2));camera.lookAt(center);camera.updateProjectionMatrix();orbit.update()};$('iso-view').onclick=fit;$('top-view').onclick=()=>view(new THREE.Vector3(0,-.001,1));$('front-view').onclick=()=>view(new THREE.Vector3(0,-1,0));$('side-view').onclick=()=>view(new THREE.Vector3(1,0,0));
window.cadforge={projectPoint:(point)=>{const p=new THREE.Vector3(...point).project(camera),r=renderer.domElement.getBoundingClientRect();return {x:r.left+(p.x+1)*r.width/2,y:r.top+(1-p.y)*r.height/2}},getState:()=>state,getSelection:()=>selected,getPreview:()=>pending,selectPart:(id)=>{const p=state.parts.find(p=>p.id===id);if(p)selectPart(p)},fit};
const saved=localStorage.getItem('cadforge-session');if(saved)api(`/sessions/${saved}`).then(s=>useState(s,true)).catch(()=>localStorage.removeItem('cadforge-session'));
